export const siteMetadata = {
  title: "infinityInfo",
  author: "Pankaj",
  headerTitle: "Info",
  description: "A blog about yojana, scheme, Results , Govt exam",
  language: "en-us",
  theme: "system",
  siteUrl: "https://yourblog.com",
  siteLogo: "/logo.svg",
  email: "your.email@example.com",
  github: "https://github.com/yourusername",
  twitter: "https://twitter.com/yourusername",
  linkedin: "https://linkedin.com/in/yourusername",
  locale: "en-US",
};
